In [1]:
import pandas as pd
import numpy as np
import pickle
import iql
import matplotlib
matplotlib.use('nbagg')
import matplotlib.pyplot as plt

/var/local/conda/install/lib/python2.7/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)


In [2]:
from scipy.stats import chi2_contingency
from scipy.stats import chi2

In [3]:
t = np.array([[1,2,3],[4,8,2],[11,11,14], [1,1,4], [9,5,1]])
t

array([[ 1,  2,  3],
       [ 4,  8,  2],
       [11, 11, 14],
       [ 1,  1,  4],
       [ 9,  5,  1]])

In [12]:
t2 = np.array([[1,2,3],[4,8,2], [2,4,6]])
print "repeat first 2 rows"
t2

repeat first 2 rows


array([[1, 2, 3],
       [4, 8, 2],
       [2, 4, 6]])

In [5]:
t_chi2, t_p, t_dof, t_exp = chi2_contingency(t)
m = t_exp[0] / t_exp[0].sum()
t_p

0.058441081152181558

In [6]:
t_omega = (t - t_exp) / np.sqrt(t_exp)
u,d,vt = np.linalg.svd(t_omega)
u_df = pd.DataFrame(u)
v_df = pd.DataFrame(vt.T)
d

array([  3.43658610e+00,   1.79619033e+00,   2.61597101e-16])

In [7]:
f=2
rs = np.diag(t.sum(axis=1)**-0.5)

row_scores = pd.DataFrame(
    np.dot(
        rs,
        np.dot(u[:,:f], np.diag(d[:f]))
    )
)

In [8]:
row_scores

0         1
0 -0.432387  0.119426
1  0.305497  0.380950
2 -0.162053 -0.041378
3 -0.754495 -0.134710
4  0.578550 -0.250132

In [13]:
rs2 = t2.sum(axis=1)
t2_omega2 = np.zeros(shape=(t2.shape), dtype=np.float)
root_m = np.sqrt(m)
for i in range(len(t2)):
    t2_omega2[i] = (t2[i] * 1.0 / rs2[i] - m) / root_m

In [14]:
row_scores_new = pd.DataFrame(
    np.dot(
        t2_omega2,
        vt.T[:,:f]
    )
)

row_scores_new

0         1
0 -0.432387  0.119426
1  0.305497  0.380950
2 -0.432387  0.119426

In [11]:
#cs = np.diag(t.sum(axis=0)**-0.5)
#col_scores = pd.DataFrame(
#    np.dot(
#        cs,
#        vt.T[:,:f]
#    )
#)
## only for plotting
#col_scores2 = pd.DataFrame(
#    np.dot(
#        cs,
#        np.dot(vt.T[:,:f], np.diag(d[:f]**0.5))
#    )
#)